image: Visual Studio 2022

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: Vsix-IncrementVsixVersion src\ExtensionManager.Vsix.2017\source.extension.vsixmanifest
  - ps: Vsix-IncrementVsixVersion src\ExtensionManager.Vsix.2019\source.extension.vsixmanifest
  - ps: Vsix-IncrementVsixVersion src\ExtensionManager.Vsix.2022\source.extension.vsixmanifest | Vsix-UpdateBuildVersion
  - ps: Vsix-TokenReplacement src\ExtensionManager.Vsix.2017\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'
  - ps: Vsix-TokenReplacement src\ExtensionManager.Vsix.2019\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'
  - ps: Vsix-TokenReplacement src\ExtensionManager.Vsix.2022\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
